### ISSUE TITLE
Blank screen Error

### ISSUE THREAD

**Issue by pranay-simejia** [vibalijoshi/List-of-Opportunities#18]
**When I press "[" key, the list disappears **

**Comment by vibalijoshi** [comment]
Thanks for your observation @pranay-simejia!
@sadn1ck what could be the reason?

**Comment by sadn1ck** [comment]
just checked, the regex fails. we can probably move from regex to simple string matching. ill send a PR unless someone wants to work on it?

![image](https://user-images.githubusercontent.com/16396161/130344792-d760489a-7506-46ee-95eb-acacc182d271.png)

**Comment by vibalijoshi** [comment]
I guess you will be the perfect man for this job ⭐
Assigning it to you ✨
