### ISSUE TITLE
Text hidden in table

### ISSUE THREAD

**Issue by Rishav-12** [vibalijoshi/List-of-Opportunities#32]
**Bug/Issue**
On the website, the text in the last column **TAG** is getting hidden. Attaching a screenshot:

![Screenshot_2021-09-26 List of Opportunities(2)](https://user-images.githubusercontent.com/76068105/134800878-19288c67-541e-4463-a13e-9f8a5e8c4f31.png)

**Comment by vibalijoshi** [comment]
Hey @Rishav-12 it is working fine for me. Could you please describe the issue in detail.

**Comment by Rishav-12** [comment]
@vibalijoshi actually there is a left-right scroll bar at the bottom of the table, which I did not notice. I was using Firefox by the way.

**Comment by vibalijoshi** [comment]
Ohh I see, I guess it is resolved then! Closing it 😇
