### ISSUE TITLE
[UPD] Tweak the table

### ISSUE THREAD

**Issue by arnabsen1729** [vibalijoshi/List-of-Opportunities#4]
Instead of putting a separate field for links, we can wrap the opportunity name with the link. Example:

**Current**
Opportunity | Deadline Date | Type | Link|
-- | -- | -- | --
Goldman Sachs WeTech | Jan 18 | Mentorship | https://www.iie.org/Programs/WeTech/STEM-Scholarships-for-Women/Goldman-Sachs-Scholarship

**Update**
Opportunity (with Link) | Deadline Date | Type | Labels/Description |
-- | -- | -- | --
[Goldman Sachs WeTech](https://www.iie.org/Programs/WeTech/STEM-Scholarships-for-Women/Goldman-Sachs-Scholarship) | Jan 18 | Mentorship | <Specify labels as mentioned in #2 >

**Advantages:**
- The table will look very uniform since right now the nonuniformity arises from the different lengths of the link.
- We can provide more info about the opportunity.

**Approach:**
Will write a small script that will do the tasks of removing the `links` column and putting them in the opportunities column.

**Comment by vibalijoshi** [comment]
This Looks great! Thanks for your suggestion @arnabsen1729

**Comment by ansi13c** [comment]
Nice suggestion.Thanks
